// GENERATED by scripts/sync-public-config.mjs — do not edit manually
class BootstrapConfig {
  BootstrapConfig._();

  static const publicBaseUrl = 'http://124.220.4.69:8081';
  static const configUrls = <String>[
    'http://124.220.4.69:8081/app-config.json',
    'http://192.168.3.21/app-config.json',
  ];
}
